name: server
description: A standalone server application written in Dart language.

version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0

repository: https://github.com/shubhanshu02/derver
